---
- name: Install Nginx
  apt: name=nginx state=present

- name: Copy default Nginx configuration for Wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx 
    
