---
- name: Create Database in MYSQL
  mysql_db: name=wordpress state=present login_user="root" login_password="password"

- name: Create user in MYSQL
  mysql_user: name=wordpressuser password=worpress priv=*.*:ALL state=present login_user="root" login_password="password"

- name: Download wordpress
  get_url: url=http://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz

- name: Unarchive wordpress
  command: chdir=/tmp/ /bin/tar xvf latest.tar.gz creates=/tmp/wordpress


- name: Configure wordpress
  template: src=wp-config.php dest=/tmp/wordpress/

- name: transfer WordPress files
  synchronize: src=/tmp/wordpress/ dest=/var/www/html/

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/wordpress/


- name: change permishions
  file: path=/var/www/html/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes
