---
- name: Create Database in MYSQL
  mysql_db: name=wordpress state=present

- name: Create user in MYSQL
  mysql_user: name=wordpressuser password=worpress priv=*.*:ALL state=present

- name: Download wordpress
  get_url: url=http://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz

- name: Unarchive wordpress
  shell: "tar xvfz /tmp/latest.tar.gz /tmp/

- name: Configure wordpress
  template: src=wp-config.php dest=/tmp/wordpress/

- name: transfer WordPress files
  synchronize: src=/tmp/wordpress/ dest=/var/www/html/

- name: change permishions
  shell: "chown -R demo:www-data /var/www/html/"