---
- name: Create Database in MYSQL
  mysql_db: name=wordpress state=present login_user="root" login_password="password"

- name: Create user in MYSQL
  mysql_user: name=wordpressuser password=password priv=*.*:ALL state=present login_user="root" login_password="password"

- name: Download wordpress
  get_url: url=http://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz

- name: Unarchive wordpress
#  unarchive: src="/tmp/wordpress.tar.gz" dest="/var/www/html/"
#  command: creates=/var/www/html/wordpress /bin/tar xvf /tmp/wordpress.tar.gz /var/www/html/wordpress
  command: /bin/tar xfz /tmp/wordpress.tar.gz -C /tmp

#- name: Copy all files to /var/www/html

- name: Configure wordpress
  template: src=wp-config.php dest=/tmp/wordpress

#- name: transfer WordPress files
#  command: "cp -R /tmp/wordpress/* /var/www/html/"
#  synchronize: src=/tmp/wordpress dest=/var/www/html recursive=yes

#- name: Add group "wordpress"
#  group: name=www-data

#- name: Add user "wordpress"
#  user: name=www-data group=wordpress home=/srv/wordpress/


- name: change permishions
  file: path=/tmp/wordpress owner=www-data group=www-data state=directory recurse=yes
