---
- name: install php-fpm and deps
  apt: name={{ item }} state=present
  with_items:
    - php-console-table
    - php-pear
    - php5-cli
    - php5-common
    - php5-curl
    - php5-dev
    - php5-gd
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-mysql
    - php5-sqlite
    - php5-xdebug
    - libapache2-mod-php5
    - php5-fpm

- name: Disable default pool
  command: mv /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.disabled creates=/etc/php5/fpm/pool.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php5/fpm/pool.d/
  notify: restart php-fpm
