---
- name: Install WordPress, MySQL, PHP, Nginx
  hosts: wordpress-server
  remote_user: user
#  become: yes
#  become_method: su

#  remote_user: user
  sudo: yes

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress


