---
- name: Install PHP
  apt: pkg={{ item }}
  with_items:
    - php5
    - php5-cgi
    - php5-fpm
    - php5-memcache
    - php5-memcached
    - php5-mcrypt
    - php5-mysql
    - php5-gd
    - php5-curl
    - php5-xmlrpc


- name: Change /etc/apache2/mods-enabled/dir.conf
  replace: dest=/etc/apache2/mods-enabled/dir.conf regexp='(DirectoryIndex)\s+index.html\s*$' replace='\1 DirectoryIndex index.php'
  notify: 
  - restart: apache2   
