---
- name: Install PHP
  apt: name={{ item }}  state=latest
  with_items:
  - php5
  - libapache2-mod-php5
  - php5-mcrypt
  - php5-cli
  - php5-gd 
  - libssh2-php

  - name: Change /etc/apache2/mods-enabled/dir.conf
    replace: dest=/etc/apache2/mods-enabled/dir.conf regexp='^(DirectoryIndex)\s+index.html\s*$' replace='\1 DirectoryIndex index.php'

 - name: Restart apache2
   notify: 
     - restart: apache2   