---
- name: Install PHP
  apt: pkg={{ item }}
  with_items:
  - php5
  - php5-mysql
  - php-apc
  - php5-xmlrpc
  - php-soap
  - php5-gd
  - php5-memcache
  - php5-memcached
  - php5-curl
  - php5-tidy
  - libapache2-mod-php5 
  - php5-mcrypt


#- name: PHP | Configuration file, php.ini
 # action: template src=templates/etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
 # tags: common

#- name: APC | Cache configuration file, apc.ini
#  action: template src=templates/etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/conf.d/apc.ini
#  tags: common


#- name: Change /etc/apache2/mods-enabled/dir.conf
#  replace: dest=/etc/apache2/mods-enabled/dir.conf regexp='(DirectoryIndex)\s+index.html\s*$' replace='\1 DirectoryIndex index.php'
#  notify: 
#  - restart: apache2  

#- name: PHP | Configuration file, php.ini
#  action: template src=templates/etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
#  tags: common

#- name: APC | Cache configuration file, apc.ini
#  action: template src=templates/etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/conf.d/apc.ini
#  tags: common 
